hmmm

diff --git a/notified b/notified
--- a/notified
+++ b/notified
@@ -2,20 +2,22 @@
 # notified: notification daemon
 #           listens for input on $FIFO
 #           and shows a notification
-# depends: lemonbar, txtw, bar.conf
+# depends: lemonbar, txtw, skroll, bar.conf
 # usage: notified &
 #        echo "hello! $(date)" > $HOME/tmp/notified
 
-# 
+# change these...
+CONFIG=${HOME}/etc/bar.conf
 FIFO=${HOME}/tmp/notified
 PIDFILE=${HOME}/tmp/notified.pid
 DELAY=3
 
 # trap & cleanup
-trap cleanup 1 2 3 6
+trap cleanup 1 2 3 6 14 15
 
-# import bar config
-test -f ${ETC}/bar.conf && . ${ETC}/bar.conf
+# set color information
+FG=''
+BG=''
 
 # cleanup
 cleanup() {
@@ -23,47 +25,109 @@ cleanup() {
 	exit
 }
 
-# show the notificaiton
-notification() {
-	MESSAGE="  ${1}  "
-	SKROLL=0
-	WIDTH=$(txtw -f '$font' -s 16 "x${MESSAGE}x")
-	if [ $WIDTH -gt 400 ]; then
-		WIDTH=400
-		SKROLL=1
+# show a notificaiton
+show_notif() {
+	set -ex
+	message="   ${1}   "
+	skroll=0
+	width=$(txtw -f '$font' -s 16 "x${message}x")
+	if [ $width -gt 400 ]; then
+		width=400
+		skroll=1
 	fi
-	XPOS=$((1920-WIDTH-20))
-	YPOS=20
+	xpos=$((1920-width-20))
+	ypos=0
 	
-	if [ $SKROLL -eq 1 ]; then
-		(echo "$MESSAGE" | skroll -n 50 -r)
+	if [ $skroll -eq 1 ]; then
+		(echo "$message" | skroll -n 50 -r)
 	else
-		(echo "%{c}${MESSAGE}%{l}"; sleep $DELAY)
-	fi | lemonbar -d -g ${WIDTH}x${height}+${XPOS}+${YPOS} \
-	     -f "$font" -F $foreground -B $background
+		(echo "%{c}${message}%{l}"; sleep ${DELAY})
+	fi | lemonbar -d -g ${width}x${height}+${xpos}+${ypos} \
+	     -f "$font" -F ${FG} -B ${BG}
+}
+
+# import the config file if it exists
+load_config() {
+	if [ -f "$CONFIG" ]; then
+		. "$CONFIG"
+	else
+		echo "error: config '${CONFIG}' does not exist! exiting."
+		exit 1
+	fi
 }
 
 # if the fifo does not exist, create it
-if [ ! -p "$FIFO" ]; then
-	rm -f "$FIFO"
-	mkfifo "$FIFO"
-fi
-
-# if the pid file exists, then notified should not run
-if [ -f "$PIDFILE" ]; then
-	if [ "$(cat $PIDFILE)" != "$$" ]; then
-		echo "error: notified is already running!"
-		exit 1
+check_fifo() {
+	if [ ! -p "$FIFO" ]; then
+		echo "warn: '${FIFO}' does not exist or is not a FIFO."
+		echo "       ...creating '${FIFO}'"
+		rm -f "$FIFO"
+		mkfifo "$FIFO"
 	fi
-else
-	echo "$$" > "$PIDFILE"
-fi
+}
 
-# 
+# if the pid file exists, then notified should not run; if it does not exist,
+# then create it and add our PID to it
+check_pid() {
+	if [ -f "$PIDFILE" ]; then
+		if [ "$(cat $PIDFILE)" != "$$" ]; then
+			echo "error: notified is already running! exiting."
+			exit 1
+		fi
+	else
+		echo "$$" > "$PIDFILE"
+	fi
+}
+
+## runtime 
+load_config
+check_pid
+check_fifo
+
+## main loop 
 while true; do
+
+	# get content form fifo
 	content="$(cat $FIFO)"
-	if [ ! -z "$content" ]; then
-		notification "${content}"
+
+	# if the fifo's content is non-null
+	if [ -n "$content" ]; then
+
+		# by default the notification message is the entire content
+		message="$content"
+
+		FG=$foreground # reset FG color
+		BG=$background # reset BG color
+
+		## check for options
+		# if the content contains a ':'
+		#if echo "$content" | grep ':'>/dev/null; then
+		case "$content" in
+		*:*)
+			opts=${content%%:*}             # the option is the text before the first ':'
+			message=${content##${opts}:}    # message is all the text after '${opts}:'
+
+			## options parsing
+			case "$opts" in
+				alert)
+					# alert: change color to red
+					FG='#ff2233'
+					BG='#000000'
+					;;
+				d*)
+					if echo "$opts" | grep 'd[0-9]'; then
+						DELAY=$(echo "$opts" | grep -o '[0-9]')
+					fi
+					;;
+				*)
+					# unrecognised option, print the whole text
+					message="$content"
+					;;
+			esac
+		;;
+		#fi
+		esac
+		show_notif "$message"
 	fi
 done
 
diff --git a/stacks b/stacks
--- a/stacks
+++ b/stacks
@@ -2,16 +2,38 @@
 # stacks: multiple bars in one script
 # depends: curl, apm, bar.sh, mpc, xtitle
 
+trap die 1 2 3 6 15
+
 # source config file
 test -f $HOME/etc/bar.conf && . $HOME/etc/bar.conf
 
+#
+PIDPATH=${HOME}/tmp/bar
 
 # stacks on stacks on stacks
 
+# kill the running stacks
+die() {
+	pkill -KILL lemonbar
+	for file in ${PIDPATH}/*; do
+		[ -f "$file" ] || continue
+		kill -KILL "$(cat ${file})"
+		rm -f "${file}"
+	done
+}
+
 # displays time
 clock() {
+	# if the pid file exists, then something is running
+	if [ -f "${PIDPATH}/clock.pid" ]; then
+		echo "error: clock bar is already running!"
+		exit 1
+	else
+		echo "$$" > "${PIDPATH}/clock.pid"
+	fi
 	while true; do
-		echo "%{c}$(date '+%H:%M:%S') | $(date '+%Y.%m.%d')"
+		#echo "%{c}$(date '+%H:%M:%S') $(date '+%Y.%m.%d')"
+		echo "%{c}%{A:notif \"$(date '+%A %d %B')\":}$(date '+%H:%M:%S')%{A}"
 		sleep 1
 	done | W=$clock_w X=$clock_x Y=$clock_y BG=$clock_bg FG=$clock_fg bar
 }
@@ -26,6 +48,14 @@ datee() {
 
 # displays battery status
 bat() {
+	# if the pid file exists, then something is running
+	if [ -f "${PIDPATH}/bat.pid" ]; then
+		echo "error: bat bar is already running!"
+		exit 1
+	else
+		echo "$$" > "${PIDPATH}/bat.pid"
+	fi
+
 	local percent status ac color charging
 	while true; do
 		percent=`apm -l`
@@ -55,6 +85,15 @@ bat() {
 
 # displays wttr info
 wttr() {
+	
+	# if the pid file exists, then something is running
+	if [ -f "${PIDPATH}/wttr.pid" ]; then
+		echo "error: wttr bar is already running!"
+		exit 1
+	else
+		echo "$$" > "${PIDPATH}/wttr.pid"
+	fi
+
 	while true; do
 		DATA=$(curl --connect-timeout 10 wttr.in/${WTTRCITY}?format=%t,%h 2>/dev/null)
 		if [ -z "$DATA" ]; then
@@ -66,43 +105,9 @@ wttr() {
 		fi
 
 		echo "%{c}${TEMP} %{F${accent}}@%{F-} ${HUM} humidity"
-		sleep 500
+		sleep 120
 	done | W=$wttr_w X=$wttr_x Y=$wttr_y BG=$wttr_bg FG=$wttr_fg bar
 }
-
-#vol() {
-#	while true; do
-#		if pgrep mpd >/dev/null; then
-#		vol="$(mixerctl outputs.master | cut -d '=' -f 2 | cut -d ',' -f 1)"
-#		mute="$(mixerctl -n outputs.master.mute)"
-#		title="$(mpc current)"
-#		text=""	
-#	
-#		if [ "$mute" = "on" ]; then
-#			text="  X  "
-#		else
-#			text="  !  "
-#		fi
-#		
-#		#if [ -z "$title" ]; then
-#		#	text="${text}  n/a  "
-#		#else
-#		#	text="${text}  ${title}  "
-#		#fi
-
-#		if [ $(echo -n "$vol" | wc -c) -eq 3 ]; then
-#			text="${text}%{R}  ${vol} %{R}"
-#		else
-#			text="${text}%{R}  ${vol}  %{R}"
-#		fi
-
-#		echo "$text"		
-#		else
-#			echo "n/a"
-#		fi	
-#		sleep 2
-#	done | W=$music_w X=$music_x Y=$music_y BG=$music_bg FG=$music_fg bar
-#}
 
 # displays current window in scrolling text
 title() {
@@ -117,12 +122,12 @@ music() {
 	while true; do
 		track=""
 		if [ ! -z "$(pgrep mpd)" ]; then
-			track="$(mpc status --format '%title% - %artist%' | head -n1)"
+			track="$(mpc status --format '%title% // %artist%' | head -n1)"
 		else
 			track="<<<<<<<<<<<<<<<<"
 		fi
-		echo "$track" | skroll -n 25 -r
-	done | BOT='no' W=$music_w X=$music_x Y=$music_y BG=$foreground FG=$background bar
+		echo "$track" | skroll -n $((($music_w / 10) + 10 )) -r
+	done | BOT='yes' W=$music_w X=$music_x Y=$music_y BG=$music_bg FG=$music_fg bar
 }
 
 
@@ -133,5 +138,6 @@ case "$1" in
 	"wttr")  wttr  ;;
 	"music") music ;;
 	"title") title ;;
+	"kill")  die  ;;
 	*)       echo "invalid stack" && exit 1 ;;
 esac
